Algoritmo "idades"

Var


   n1, n2 : caractere
   id1, id2 : inteiro
   media : real

Inicio


   escreval("Dados da primeira pessoa:")
   escreval("Nome: ")
   leia(n1)
   escreval("Idade: ")
   leia(id1)
   
   escreval("Dados da segunda pessoa:")
   escreval("Nome: ")
   leia(n2)
   escreval("Idade: ")
   leia(id2)
   
   media <- (id1 + id2) / 2

   escreval("A idade media de Maria Silva e Joao Melo é de  ", media)

Fimalgoritmo